exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start nixos-fake-graphical-session.target
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --watch cliphist store
exec-once = wlsunset -S 05:30 -s 17:40
exec-once = libinput-gestures
