# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
windowrule {
  name = suppress-maximize-events
  match:class = .*
  suppress_event = maximize
}

# Focus browser when activated (e.g. opening a link from another app)
windowrule = focus_on_activate on, match:class ^(helium-browser|Chromium|Brave-browser)$

# Force chromium into a tile to deal with --app bug
windowrule {
  name = tile-chromium
  match:class = ^(Chromium)$
  tile = true
}
windowrule {
  name = tile-brave
  match:class = ^(Brave-browser)$
  tile = true
}

# Float and center sound, bluetooth, and wifi settings, as well as file manager previews
windowrule {
  name = float-system-dialogs
  match:class = ^(org.pulseaudio.pavucontrol|blueberry.py|org.gnome.NautilusPreviewer)$
  float = true
  size = 800 600
  center = true
}

# Float and center file pickers
windowrule {
  name = float-file-pickers
  match:class = ^(xdg-desktop-portal-gtk)$
  match:title = ^(Open.*Files?|Save.*Files?)
  float = true
  center = true
}

# Just dash of opacity
windowrule {
  name = default-opacity
  match:class = .*
  opacity = 0.97 0.9
}
windowrule {
  name = browser-opacity
  match:class = ^(Chromium|chromium|Brave-browser|brave-browser)$
  opacity = 1 0.97
}
windowrule {
  name = youtube-opacity
  match:initial_title = ^(youtube.com/)$
  opacity = 1 1
}
windowrule {
  name = media-opacity
  match:class = ^(zoom|vlc|mpv|imv)$
  opacity = 1 1
}

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
  no_focus = true
}

# Proper background blur for wofi
layerrule {
  name = blur-wofi
  match:namespace = wofi
  blur = true
}
